### ISSUE TITLE
Theme support for Material Discord

### ISSUE THREAD

**Issue by Zan1456** [s-k-y-l-i/discord-themes#1]
Hi! Maybe you could make the theme to support [Material Discord](https://github.com/CapnKitten/Material-Discord)?
![image](https://github.com/s-k-y-l-i/discord-themes/assets/62830223/9b11427f-4b4b-42db-9451-c884cf1ec890)

**Comment by s-k-y-l-i** [comment]
Szia! :D 

What do you mean? You want to add transparency to that theme?

**Comment by Zan1456** [comment]
Igen

**Comment by s-k-y-l-i** [comment]
If you use this: `https://raw.githubusercontent.com/s-k-y-l-i/discord-themes/main/acrylic-harmony-transparent-frame.css`
it already works perfectly, enabling mica on the titlebar and the server bar.
![image](https://github.com/s-k-y-l-i/discord-themes/assets/7442913/af01986f-ba35-4d21-a786-951ad6bcc462)

**Comment by Zan1456** [comment]
What if I want it almost completely transparent?

**Comment by s-k-y-l-i** [comment]
Try this:
``` css
:root{
    --var-opacity-option: 0.8;    /*   Acrylic opacity from 0 to 1    */
    --var-color-saturation: 1; /* 0 to 999 where 1 is the default  */
    --var-contrast: 1.07;          /*     Increase for darker blacks   */
    --var-background:80%;
    --var-bubbles:30%;
}



/* MICA */
body, #app-mount,
.typeWindows__5fa63,
.app_de4237,.bg__12180,
.guilds__2b93a,.scroller__3d071 {
        background: transparent !important;
}

/* Darker transparency background*/

body {
    position: relative;
}

body::before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: var(--bg-overlay-app-frame,var(--background-tertiary));
    opacity: var(--var-opacity-option); /* Átlátszóság beállítása (0-től 1-ig terjedő értékek) */
    z-index: -1; /* Az átlátszó háttér mögé helyezése */
    filter: saturate(var(--var-color-saturation)) contrast(var(--var-contrast));
}

.container__590e2::after,.children__32014::after{display: none!important;}

.sidebar_ded4b5, #vc-spotify-player, .sidebar_ded4b5 .container__590e2,
.sidebar_ded4b5 .container__7c79d:not(.hasBanner_e78601) .header__104ca, 
.privateChannels__93473, .chat__52833,.container__11d72.themed_b152d4,
.form__13a2c,.container_b2ce9c,.members__9f47b, .members__9f47b > div,
 .wrapper__09ecc,.form__13a2c .scrollableContainer__33e06,.container_ca50b9
 {
background-color: color-mix( in srgb, currentColor , 
    transparent 100%) !important;
}

.content__4bf10 { 
    background-color: color-mix( in srgb, currentColor , 
    transparent var(--var-background)) !important;}

.form__13a2c .scrollableContainer__33e06,.search_ac353c .searchBar_e0c60b,.wrapper__09ecc, #vc-spotify-player, .container_ca50b9{ 
    background-color: color-mix( in srgb, var(--main-textarea-color), 
    transparent var(--var-bubbles)) !important;}
```
